### ISSUE TITLE
不支持中文html文件名搜索

### ISSUE THREAD

**Issue by fgm0129** [dushao103500/static-server#1]
遇到这样的需求，需要部署下产品的prd文档，里面的html和文件夹名称都是中文的，可以修改下decodeURI(req.url),支持下中文链接，你看下是否可以更新下，谢谢。

**Comment by WisestCoder** [comment]
@fgm0129 不忙的话，可以提pr

**Comment by WisestCoder** [comment]
已经fix，新版本0.0.10
